
package PurchaseManager;

import admin.AdminDashboard;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import shared.utils.PurchaseOrderUtils;

public class GeneratePurchaseOrderForm extends javax.swing.JFrame {

    private PMDashboard previousPMForm;
    private AdminDashboard previousAdminForm;
    private String purchaseManagerId; // this field to store the PM ID     
     
    public GeneratePurchaseOrderForm() {
        initComponents();
        setupTableListeners();
        loadPendingPurchaseRequisitions();
        loadPurchaseOrders();
    }
    public GeneratePurchaseOrderForm(PMDashboard previousForm) {
        this();
        this.previousPMForm = previousForm;
        this.purchaseManagerId = previousForm.getUserId(); // Get the PM ID from the dashboard        
    }
    
    // Add a new constructor for AdminDashboard
    public GeneratePurchaseOrderForm(AdminDashboard previousForm) {
        this();
        this.previousAdminForm = previousForm;
        this.purchaseManagerId = previousForm.getUserId(); // Get the Admin ID from the dashboard
    }    

    private void setupTableListeners() {
        // Add selection listener to the pending PR table
        jTable2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable2.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int selectedRow = jTable2.getSelectedRow();
                    generatePOButton.setEnabled(selectedRow >= 0);
                }
            }
        });
    }

    private void loadPendingPurchaseRequisitions() {
        try {
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            PurchaseOrderUtils.loadPendingPRsToTable(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                    "Error loading pending purchase requisitions: " + e.getMessage(),
                    "Database Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void loadPurchaseOrders() {
        try {
            DefaultTableModel model = (DefaultTableModel) poTable.getModel();
            PurchaseOrderUtils.loadPurchaseOrdersToTable(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                    "Error loading purchase orders: " + e.getMessage(),
                    "Database Error", 
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameBG = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        titleGeneratePurchaseOrder = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        txtPendingPurchaseRequitions = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        bottomPanel = new javax.swing.JPanel();
        txtPurchaseOrders = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        poTable = new javax.swing.JTable();
        ButtonPanel = new javax.swing.JPanel();
        generatePOButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generate Purchase Order");
        setPreferredSize(new java.awt.Dimension(1100, 780));

        FrameBG.setBackground(new java.awt.Color(255, 255, 255));
        FrameBG.setAlignmentX(0.0F);
        FrameBG.setAlignmentY(0.0F);
        FrameBG.setPreferredSize(new java.awt.Dimension(750, 550));

        titlePanel.setBackground(new java.awt.Color(255, 255, 204));
        titlePanel.setAlignmentX(0.0F);
        titlePanel.setAlignmentY(0.0F);
        titlePanel.setPreferredSize(new java.awt.Dimension(706, 70));
        titlePanel.setLayout(new java.awt.BorderLayout());

        titleGeneratePurchaseOrder.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        titleGeneratePurchaseOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleGeneratePurchaseOrder.setText("Generate Purchase Order");
        titleGeneratePurchaseOrder.setAlignmentY(0.0F);
        titleGeneratePurchaseOrder.setMaximumSize(new java.awt.Dimension(237, 30));
        titleGeneratePurchaseOrder.setMinimumSize(new java.awt.Dimension(237, 30));
        titleGeneratePurchaseOrder.setPreferredSize(new java.awt.Dimension(237, 30));
        titlePanel.add(titleGeneratePurchaseOrder, java.awt.BorderLayout.CENTER);

        topPanel.setBackground(new java.awt.Color(255, 255, 255));
        topPanel.setLayout(new java.awt.BorderLayout());

        txtPendingPurchaseRequitions.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtPendingPurchaseRequitions.setText("    Pending Purchase Requitions");
        topPanel.add(txtPendingPurchaseRequitions, java.awt.BorderLayout.PAGE_START);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "PR ID", "Item ID", "Item Name", "Quantity", "Date Required", "Status", "Requested By(SM ID)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        topPanel.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        bottomPanel.setBackground(new java.awt.Color(255, 255, 255));
        bottomPanel.setLayout(new java.awt.BorderLayout());

        txtPurchaseOrders.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txtPurchaseOrders.setText("   Purchase Orders");
        bottomPanel.add(txtPurchaseOrders, java.awt.BorderLayout.PAGE_START);

        poTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "PO ID", "PR ID", "Item ID", "Item Name", "Quantity", "Item Price", "Total Price", "Date Created PO", "Date Required", "Supplier ID", "SM ID", "PM ID", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(poTable);

        bottomPanel.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        ButtonPanel.setBackground(new java.awt.Color(255, 255, 255));

        generatePOButton.setBackground(new java.awt.Color(0, 204, 102));
        generatePOButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        generatePOButton.setForeground(new java.awt.Color(255, 255, 255));
        generatePOButton.setText("Generate Purchase Order");
        generatePOButton.setEnabled(false);
        generatePOButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatePOButtonActionPerformed(evt);
            }
        });
        ButtonPanel.add(generatePOButton);

        refreshButton.setBackground(new java.awt.Color(33, 150, 243));
        refreshButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        refreshButton.setForeground(new java.awt.Color(255, 255, 255));
        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        ButtonPanel.add(refreshButton);

        backButton.setBackground(new java.awt.Color(102, 102, 102));
        backButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        ButtonPanel.add(backButton);

        javax.swing.GroupLayout FrameBGLayout = new javax.swing.GroupLayout(FrameBG);
        FrameBG.setLayout(FrameBGLayout);
        FrameBGLayout.setHorizontalGroup(
            FrameBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameBGLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FrameBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1088, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(FrameBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1091, Short.MAX_VALUE))
        );
        FrameBGLayout.setVerticalGroup(
            FrameBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameBGLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(FrameBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(FrameBGLayout.createSequentialGroup()
                    .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 698, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FrameBG, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FrameBG, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // Modified to handle both types of previous forms
        if (previousPMForm != null) {
            previousPMForm.setVisible(true);
        } else if (previousAdminForm != null) {
            previousAdminForm.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void generatePOButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatePOButtonActionPerformed
        int selectedRow = jTable2.getSelectedRow();
        if (selectedRow < 0) {
            return; // No row selected
        }

        try {
            // Get PR details from the table
            String prId = jTable2.getValueAt(selectedRow, 0).toString();
            String itemId = jTable2.getValueAt(selectedRow, 1).toString();
            String itemName = jTable2.getValueAt(selectedRow, 2).toString();
            int quantity = Integer.parseInt(jTable2.getValueAt(selectedRow, 3).toString());
            String dateRequired = jTable2.getValueAt(selectedRow, 4).toString();
            String salesManagerId = jTable2.getValueAt(selectedRow, 6).toString();

            // Pass the purchaseManagerId to the dialog
            AddPurchaseOrderDialog dialog = new AddPurchaseOrderDialog(
                    this, true, prId, itemId, itemName, quantity, dateRequired, 
                    salesManagerId, purchaseManagerId); // Add purchaseManagerId here

            // Position the dialog relative to this form
            dialog.setLocationRelativeTo(this);

            // Show dialog
            dialog.setVisible(true);

            // If confirmed, refresh the tables
            if (dialog.isConfirmed()) {
                loadPendingPurchaseRequisitions();
                loadPurchaseOrders();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                    "Error generating Purchase Order: " + e.getMessage(),
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_generatePOButtonActionPerformed
    private String getItemName(String itemId) {
        try {
            java.io.File file = new java.io.File("src/database/items.txt");
            if (!file.exists()) {
                return "";
            }
            
            try (java.io.BufferedReader reader = new java.io.BufferedReader(
                    new java.io.FileReader(file))) {
                String line;
                boolean headerSkipped = false;
                
                while ((line = reader.readLine()) != null) {
                    // Skip header line
                    if (!headerSkipped) {
                        headerSkipped = true;
                        continue;
                    }
                    
                    // Skip empty lines
                    if (line.trim().isEmpty()) {
                        continue;
                    }
                    
                    String[] parts = line.split(",");
                    if (parts.length >= 2 && parts[0].trim().equals(itemId)) {
                        return parts[1].trim();
                    }
                }
            }
            
            return "";
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                    "Error finding item name: " + e.getMessage(),
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            return "";
        }
    }
    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        loadPendingPurchaseRequisitions();
        loadPurchaseOrders();
    }//GEN-LAST:event_refreshButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneratePurchaseOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneratePurchaseOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneratePurchaseOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneratePurchaseOrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneratePurchaseOrderForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JPanel FrameBG;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton generatePOButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable poTable;
    private javax.swing.JButton refreshButton;
    private javax.swing.JLabel titleGeneratePurchaseOrder;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel txtPendingPurchaseRequitions;
    private javax.swing.JLabel txtPurchaseOrders;
    // End of variables declaration//GEN-END:variables
}
